{% set name = "whey" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whey-{{ version }}.tar.gz
  sha256: 846bde196c5116571801237e546a55fa7d25fc984071bd10c4460bd4db659b37

build:
  entry_points:
    - whey = whey.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=22.2.0
    - click >=7.1.2
    - consolekit >=1.4.1
    - dist-meta >=0.1.0
    - dom-toml >=0.4.0
    - domdf-python-tools >=2.8.0
    - handy-archives >=0.2.0
    - natsort >=7.1.1
    - packaging >=20.9
    - pyproject-parser >=0.6.0
    - python >=3.6
    - shippinglabel >=0.16.0

test:
  imports:
    - whey
  commands:
    - pip check
    - whey --help
  requires:
    - pip

about:
  home: https://github.com/repo-helper/whey
  summary: A simple Python wheel builder for simple projects.
  license: MIT
  license_file: LICENSE
  doc_url: https://whey.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
